services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: minha_api_dev
    restart: always
    environment:
      - NODE_ENV=development
      - DB_HOST=meu_postgres
      - DB_USER=meu_usuario
      - DB_PASSWORD=minha_senha
      - DB_NAME=meu_banco
      - DB_PORT=5432
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    environment:
      - POSTGRES_USER=meu_usuario
      - POSTGRES_PASSWORD=minha_senha
      - POSTGRES_DB=meu_banco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: meu_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata: 