services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: meu_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api:
    build: .
    container_name: minha_api
    restart: always
    environment:
      DB_HOST: postgres
      DB_USER: meu_usuario
      DB_PASSWORD: minha_senha
      DB_NAME: meu_banco
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata: 